version: 2.1
orbs:
    react: thefrontside/react@0.2.0
jobs:
    deploy:
        docker:
            - image: circleci/node:latest
        steps:
            - checkout
            - run: npm install ftp-deploy
            - run: node .circleci/deploy.js
            - run: echo "WE'RE ONLINE"
workflows:
    push:
        jobs:
            - react/install
            - react/eslint:
                  requires:
                      - react/install
            - react/build:
                  requires:
                      - react/install
                      - react/eslint
            - deploy:
                  requires:
                      - react/build
